#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Translate luci-app-qosify main.js to Simplified Chinese (in-place on qosify-luci.sh).
# Generated translation table: 295 entries, keyed by the exact English _('...') string.
import re, sys

T = {
"List of files with port/IP/host mappings": "包含端口/IP/主机映射的文件列表",
"Default timeout for dynamically added entries": "动态添加条目的默认超时时间",
"Default DSCP value for TCP packets": "TCP 数据包的默认 DSCP 值",
"Default DSCP value for UDP packets": "UDP 数据包的默认 DSCP 值",
"DSCP value for ICMP packets": "ICMP 数据包的 DSCP 值",
"DSCP value for priority-marked packets": "优先级标记数据包的 DSCP 值",
"DSCP value for bulk-marked packets": "批量标记数据包的 DSCP 值",
"Maximum average packet length for marking a flow as priority": "将流标记为优先级的最大平均数据包长度",
"Number of packets per second to trigger bulk flow detection": "触发批量流检测的每秒数据包数",
"Time below bulk_trigger_pps threshold until a bulk flow mark is removed": "低于 bulk_trigger_pps 阈值直至移除批量流标记的时间",
"DSCP value for ingress and egress, where they are not set": "入站和出站 DSCP 值，未单独设置时生效",
"DSCP value for ingress": "入站 DSCP 值",
"DSCP value for egress": "出站 DSCP 值",
"netifd interface (config interface) or netdev (config device) to enable QoS on": "要启用 QoS 的 netifd 接口（config interface）或网络设备（config device）",
"Skip this section": "跳过此小节",
"Uplink bandwidth (same format as tc)": "上行带宽（与 tc 格式相同）",
"Downlink bandwidth (same format as tc)": "下行带宽（与 tc 格式相同）",
"Bandwidth for both directions, where bandwidth_up or bandwidth_down is not set": "双向带宽，当未设置 bandwidth_up 或 bandwidth_down 时生效",
"Enable ingress shaping": "启用入站整形",
"Enable egress shaping": "启用出站整形",
"CAKE diffserv mode": "CAKE diffserv 模式",
"Enable CAKE NAT host detection via conntrack": "通过 conntrack 启用 CAKE NAT 主机检测",
"Enable CAKE host isolation": "启用 CAKE 主机隔离",
"Enable CAKE automatic rate estimation for ingress": "为入站启用 CAKE 自动速率估算",
"CAKE overhead keyword added to options; manual uses overhead and overhead_encap": "CAKE overhead 关键字会加入选项；manual 使用 overhead 和 overhead_encap",
"Adds overhead <bytes> when overhead_type is manual": "当 overhead_type 为 manual 时添加 overhead <字节>",
"Adds atm, noatm or ptm when overhead_type is manual": "当 overhead_type 为 manual 时添加 atm、noatm 或 ptm",
"Adds mpu <bytes>": "添加 mpu <字节>",
"Adds ether-vlan once per level (1 or 2)": "每层添加一次 ether-vlan（1 或 2）",
"CAKE ingress options": "CAKE 入站选项",
"CAKE egress options": "CAKE 出站选项",
"CAKE options for ingress + egress": "CAKE 入站 + 出站选项",
"Binary content rejected": "已拒绝二进制内容",
"Line %d is longer than 1023 characters — the rule loader reads fixed-size lines and would split it": "第 %d 行超过 1023 个字符 — 规则加载器按固定行宽读取，会将其截断",
"name is not set — qosify.init sends an empty device name and this section is never applied": "未设置 name — qosify.init 会发送空设备名，此小节永远不会生效",
"nat is not sent: qosify only emits nat/nonat inside the host_isolate branch. CAKE does accept flows plus nat — put nat in options to apply it": "nat 不会发送: qosify 仅在 host_isolate 分支内输出 nat/nonat。CAKE 接受 flows 加 nat — 如需应用，请将 nat 放入 options",
"nat only reaches %s — put it in options, or in both ingress_options and egress_options": "nat 仅作用于 %s — 请将其放入 options，或同时放入 ingress_options 和 egress_options",
"overhead and overhead_encap are ignored unless overhead_type is manual": "除非 overhead_type 为 manual，否则 overhead 和 overhead_encap 会被忽略",
"ingress and egress are both 0 — nothing is shaped": "入站和出站均为 0 — 没有整形",
"no bandwidth_up or bandwidth — egress CAKE runs unlimited": "没有 bandwidth_up 或 bandwidth — 出站 CAKE 无限制运行",
"no bandwidth_down or bandwidth — ingress CAKE runs unlimited": "没有 bandwidth_down 或 bandwidth — 入站 CAKE 无限制运行",
"%s is set to \"%s\" — qosify converts it with atoi(), so anything but a non-zero number means off": "%s 被设置为 \"%s\" — qosify 使用 atoi() 转换，因此除非零数字外的任何值都表示关闭",
"disabled is set to \"%s\" — config_get_bool does not recognise that, so the section stays enabled": "disabled 被设置为 \"%s\" — config_get_bool 无法识别，因此该小节保持启用",
"%s contains shell metacharacters — qosify assembles the tc command as a string and runs it with sh -c, so the command will break or execute them": "%s 包含 shell 元字符 — qosify 会把 tc 命令拼成字符串并用 sh -c 执行，因此命令可能出错或被执行",
"%s is a list in this section — edit %s directly": "%s 在此小节中是列表 — 请直接编辑 %s",
"No DSCP target on line %s — qosify skips single-field lines": "第 %s 行没有 DSCP 目标 — qosify 会跳过单字段行",
"Unknown class/DSCP target: %s": "未知的类别/DSCP 目标: %s",
"Cancel": "取消",
"Continue": "继续",
"The qosify UCI configuration could not be loaded — class and interface lists may be incomplete.": "无法加载 qosify 的 UCI 配置 — 类别和接口列表可能不完整。",
"qosify": "qosify",
"Traffic shaping and DSCP classification via qosify": "通过 qosify 进行流量整形和 DSCP 分类",
"Overview": "概览",
"Config": "配置",
"Rules": "规则",
"Status": "状态",
"Counters": "计数器",
"Advanced": "高级",
"You have read-only access to this page, so editing and service control are disabled.": "您对此页面只有只读权限，因此编辑和服务控制已禁用。",
"Service": "服务",
"Files": "文件",
"%s (current)": "%s (当前)",
"Only sent with host isolation on — add nat to common CAKE options to force it": "仅在启用主机隔离时发送 — 如需强制启用，请将 nat 添加到常用 CAKE 选项中",
"Manual overhead": "手动开销",
"Sent to CAKE as overhead, in bytes.": "以 overhead 形式（字节）发送给 CAKE。",
"Encapsulation overhead": "封装开销",
"Sent to CAKE as atm, noatm or ptm.": "以 atm、noatm 或 ptm 形式发送给 CAKE。",
"Basic": "基本",
"QoS Enabled": "QoS 已启用",
"Unticked sets disabled 1 and qosify skips this section.": "取消勾选会设置 disabled=1，qosify 将跳过此小节。",
"Device": "设备",
"Interface": "接口",
"e.g. %s": "例如 %s",
"Netdev to enable QoS on. Required.": "要启用 QoS 的网络设备。必填。",
"netifd interface to enable QoS on. Required.": "要启用 QoS 的 netifd 接口。必填。",
"Upload bandwidth": "上传带宽",
"Uplink bandwidth, same format as tc. Set just below line speed.": "上行带宽，格式与 tc 相同。设置为略低于线路速率。",
"Download bandwidth": "下载带宽",
"Downlink bandwidth, same format as tc. Set just below line speed.": "下行带宽，格式与 tc 相同。设置为略低于线路速率。",
"Queueing mode": "队列模式",
"CAKE diffserv mode.": "CAKE diffserv 模式。",
"Shaping": "整形",
"Download shaping": "下载整形",
"Enable ingress shaping.": "启用入站整形。",
"Upload shaping": "上传整形",
"Enable egress shaping.": "启用出站整形。",
"Automatic download rate": "自动下载速率",
"Enable CAKE automatic rate estimation for ingress.": "为入站启用 CAKE 自动速率估算。",
"NAT awareness": "NAT 感知",
"Enable CAKE NAT host detection via conntrack.": "通过 conntrack 启用 CAKE NAT 主机检测。",
"Host isolation": "主机隔离",
"Enable CAKE host isolation.": "启用 CAKE 主机隔离。",
"Overhead": "开销",
"Overhead preset": "开销预设",
"CAKE overhead keyword. Use none if unsure.": "CAKE overhead 关键字。不确定时使用 none。",
"Minimum packet unit (MPU)": "最小数据包单元（MPU）",
"Sent to CAKE as mpu, in bytes.": "以 mpu 形式（字节）发送给 CAKE。",
"VLAN tags": "VLAN 标签",
"Sent to CAKE as ether-vlan, once per tag.": "以 ether-vlan 形式发送给 CAKE，每标签一次。",
"Ingress CAKE options": "入站 CAKE 选项",
"CAKE ingress options, space separated.": "CAKE 入站选项，以空格分隔。",
"Egress CAKE options": "出站 CAKE 选项",
"CAKE egress options, space separated.": "CAKE 出站选项，以空格分隔。",
"Common CAKE options": "常用 CAKE 选项",
"CAKE options for ingress + egress.": "CAKE 入站 + 出站选项。",
"Invalid CAKE options can stop qosify starting.": "无效的 CAKE 选项可能导致 qosify 无法启动。",
"%s quick settings": "%s 快速设置",
"Save & Apply": "保存并应用",
"Start": "启动",
"Restart": "重启",
"Reload": "重载",
"Reload Rules": "重载规则",
"Stop": "停止",
"Re-read the mapping files only": "仅重新读取映射文件",
"rpcd is not answering for qosify, so the service state is unknown.": "rpcd 未响应 qosify，因此服务状态未知。",
"qosify did not come up — check the system log": "qosify 未能启动 — 请检查系统日志",
"Status Unknown": "状态未知",
"Active": "活动",
"Enabled — Not Shaping (check config)": "已启用 — 未整形（请检查配置）",
"Enabled — Not Running": "已启用 — 未运行",
"Disabled": "已禁用",
"Unknown": "未知",
"Running — Shaping Unknown": "运行中 — 整形状态未知",
"Running & Shaping": "运行中并整形",
"Running — Not Shaping": "运行中 — 未整形",
"Not Running": "未运行",
"rpcd is not answering for qosify — check the ACL in /usr/share/rpcd/acl.d and restart rpcd": "rpcd 未响应 qosify — 请检查 /usr/share/rpcd/acl.d 中的 ACL 并重启 rpcd",
"Enabled": "已启用",
"none": "无",
"Available": "可用",
"Missing": "缺失",
"Uptime": "运行时间",
"Autostart": "自动启动",
"device %s": "设备 %s",
"interface %s": "接口 %s",
"active": "活动",
"inactive": "未活动",
"device: %s, ingress: %s, egress: %s": "设备: %s，入站: %s，出站: %s",
"yes": "是",
"no": "否",
"Autostart state unknown — rpcd did not answer": "自动启动状态未知 — rpcd 未响应",
"Click to disable autostart": "点击禁用自动启动",
"Click to enable autostart": "点击启用自动启动",
"Valid": "有效",
"Found (empty or invalid)": "已找到（为空或无效）",
"File": "文件",
"Entries": "条目",
"Size": "大小",
"Modified": "已修改",
"section type": "小节类型",
"section name": "小节名称",
"Add": "添加",
"Section name is the class name that rules and dscp_* values refer to. qosify.init reads config alias the same way as config class.": "小节名称是规则和 dscp_* 值引用的类别名称。qosify.init 以与 config class 相同的方式读取 config alias。",
"config device takes the same options, with name set to a netdev. nat defaults to 1 for interfaces and 0 for devices.": "config device 使用相同的选项，name 设置为网络设备。nat 在接口中默认为 1，在设备中默认为 0。",
"Quick Add: %s": "快速添加: %s",
"Options": "选项",
"Reference": "参考",
"DSCP values": "DSCP 值",
"DSCP codepoints: CS0–CS7, AF11–AF43, EF, VA, NQB, LE, DF. A raw value from 0 to 63 is accepted too, and any dscp_* value may also name a class. Prefix with + to override only when the DSCP field is zero.": "DSCP 代码点: CS0–CS7、AF11–AF43、EF、VA、NQB、LE、DF。也接受 0 到 63 的原始值，任何 dscp_* 值也可以命名类别。前缀 + 表示仅在 DSCP 字段为零时覆盖。",
"Defaults": "默认值",
"Defaults qosify applies when a key is absent — interface: mode diffserv4, ingress 1, egress 1, nat 1, host_isolate 1, autorate_ingress 0. device: identical except nat 0. defaults: timeout 3600, dscp_default_tcp/udp CS0, dscp_prio/dscp_bulk/dscp_icmp unset, bulk_trigger_pps/bulk_trigger_timeout/prio_max_avg_pkt_len 0 (disabled).": "缺失键时 qosify 应用的默认值 — interface: mode diffserv4、ingress 1、egress 1、nat 1、host_isolate 1、autorate_ingress 0。device: 相同但 nat 为 0。defaults: timeout 3600、dscp_default_tcp/udp CS0、dscp_prio/dscp_bulk/dscp_icmp 未设置、bulk_trigger_pps/bulk_trigger_timeout/prio_max_avg_pkt_len 0（禁用）。",
"No classes defined in %s": "%s 中未定义类别",
"ingress %s, egress %s": "入站 %s，出站 %s",
"(alias)": "（别名）",
"Classes": "类别",
"Clear": "清空",
"Quick Add": "快速添加",
"Mapping file syntax": "映射文件语法",
"Each line has two whitespace separated fields, match and dscp. dscp can be a raw value, a codepoint like CS0, or a class name. DNS entries are compared in the order in which they are specified, using the first matching entry.": "每行有两个以空白分隔的字段: 匹配项和 dscp。dscp 可以是原始值、像 CS0 这样的代码点，或类别名称。DNS 条目按指定顺序比较，使用第一个匹配的条目。",
"TCP single port, or range from <port> to <endport>": "TCP 单端口，或从 <port> 到 <endport> 的范围",
"UDP single port, or range from <port> to <endport>": "UDP 单端口，或从 <port> 到 <endport> 的范围",
"IPv4 address, e.g. 1.1.1.1": "IPv4 地址，例如 1.1.1.1",
"IPv6 address, e.g. ff01::1": "IPv6 地址，例如 ff01::1",
"fnmatch() pattern supporting * and ? as wildcard characters": "支持 * 和 ? 通配符的 fnmatch() 模式",
"POSIX.2 extended regular expression for matching hostnames. Only works if dns lookups are passed to qosify via the add_dns_host ubus call.": "用于匹配主机名的 POSIX.2 扩展正则表达式。仅当通过 add_dns_host ubus 调用将 DNS 查询传递给 qosify 时有效。",
"Like dns:... but only matches cname entries": "类似 dns:... 但仅匹配 cname 条目",
"Only override the DSCP value if it is zero": "仅当 DSCP 值为零时才覆盖",
"No file selected": "未选择文件",
"Choose file…": "选择文件…",
"Backup": "备份",
"Download the current files from the router.": "从路由器下载当前文件。",
"Download": "下载",
"Restore": "还原",
"The selected files replace the ones on the router and qosify is reloaded.": "所选文件将替换路由器上的文件，并重载 qosify。",
"Upload": "上传",
"Upload & Apply": "上传并应用",
"Maintenance": "维护",
"Re-check devices": "重新检查设备",
"Check Devices": "检查设备",
"Re-runs the daemon\\'s own device pass: every shaped section is looked up again, one whose device now exists is started and one whose device has gone is stopped. Nothing is reported back by the call — the result shows in the Service table on the Overview tab.": "重新运行守护进程自身的设备扫描: 重新查找每个整形小节，设备现在存在的会启动，设备已消失的会停止。该调用不会返回任何结果 — 结果会显示在概览标签页的服务表中。",
"Restore qosify defaults": "还原 qosify 默认值",
"Reset": "重置",
"Could not read %s: %s": "无法读取 %s: %s",
"qosify-status": "qosify-status",
"DNS Entries (%d of %d)": "DNS 条目（%d/%d）",
"DNS Entries (%d)": "DNS 条目（%d）",
"Traffic by Class": "按类别的流量",
"Traffic by CAKE Tin": "按 CAKE Tin 的流量",
"Loading...": "加载中...",
"DNS Entries": "DNS 条目",
"share": "共享",
"total": "总计",
"No per-class counters.": "无按类别计数器。",
"Requires write access.": "需要写入权限。",
"No CAKE tin statistics.": "无 CAKE tin 统计。",
"No output.": "无输出。",
"qosify is not running. Start from the Overview tab.": "qosify 未运行。请在概览标签页启动。",
"get_stats did not answer.": "get_stats 未响应。",
"No DNS entries.": "无 DNS 条目。",
"The detailed tc output needs write access to this page.": "查看详细的 tc 输出需要此页面的写入权限。",
"Reading tc output...": "正在读取 tc 输出...",
"qosify-status returned no output.": "qosify-status 无输出。",
"Working": "运行中",
"Re-reading the mapping files...": "正在重新读取映射文件...",
"Mapping files reloaded.": "映射文件已重载。",
"Reload failed: %s": "重载失败: %s",
"Re-checking devices...": "正在重新检查设备...",
"Device check done.": "设备检查完成。",
"Device check failed: %s": "设备检查失败: %s",
"Sending %s to qosify...": "正在向 qosify 发送 %s...",
"qosify is still running — leaving the qdiscs alone": "qosify 仍在运行 — 保持 qdisc 不变",
"Cleanup exited with code %d": "cleanup 以退出码 %d 结束",
"Service action failed: %s": "服务操作失败: %s",
"Error: invalid characters in options fields. Use alphanumeric, spaces, hyphens, dots, colons only.": "错误: 选项字段包含无效字符。仅允许字母数字、空格、连字符、句点和冒号。",
"bandwidth_up does not look like a tc rate (100mbit, 12MBps, unlimited) — passing it through anyway": "bandwidth_up 看起来不是 tc 速率格式（100mbit、12MBps、unlimited）— 仍将原样传递",
"bandwidth_down does not look like a tc rate (100mbit, 12MBps, unlimited) — passing it through anyway": "bandwidth_down 看起来不是 tc 速率格式（100mbit、12MBps、unlimited）— 仍将原样传递",
"Error: overhead_mpu must be a whole number of bytes": "错误: overhead_mpu 必须是整数字节数",
"Error: overhead must be a whole number of bytes": "错误: overhead 必须是整数字节数",
"Note: bandwidth not set — CAKE will run unlimited on that direction.": "注意: 未设置带宽 — CAKE 将在该方向上无限制运行。",
"Error: name must be a device or interface name": "错误: 名称必须是设备名或接口名",
"Saving": "正在保存",
"Saving settings and applying...": "正在保存设置并应用...",
"%s came back empty although it is %d bytes on disk — refusing to overwrite it": "%s 在磁盘上有 %d 字节但读取结果为空 — 拒绝覆盖它",
"Settings saved": "设置已保存",
"Save failed: %s": "保存失败: %s",
"File changed on disk": "磁盘上的文件已变化",
"%s has changed since this editor was loaded. Saving now discards those changes.": "自编辑器加载后 %s 已变化。现在保存将丢弃这些更改。",
"Overwrite": "覆盖",
"Error: No valid config stanzas found.": "错误: 未找到有效的配置段。",
"%s is %d bytes on disk but was never loaded into the editor — refusing to truncate it. Reload the page first.": "%s 在磁盘上有 %d 字节但从未载入编辑器 — 拒绝截断它。请先刷新页面。",
"Clear configuration": "清空配置",
"An empty %s stops all shaping. Continue?": "空的 %s 将停止所有整形。继续？",
"Write empty file": "写入空文件",
"Config cleared, qosify stopped.": "配置已清空，qosify 已停止。",
"Config cleared.": "配置已清空。",
"Writing config and reloading qosify...": "正在写入配置并重载 qosify...",
"Config saved": "配置已保存",
"%s, applied (QoS disabled).": "%s，已应用（QoS 已禁用）。",
"%s, applied.": "%s，已应用。",
"%s, applied — qosify did not answer on ubus, so shaping could not be checked.": "%s，已应用 — qosify 未在 ubus 上应答，因此无法检查整形状态。",
"Warning: %s but qosify is not shaping traffic — check the Status tab.": "警告: %s 但 qosify 未对流量整形 — 请检查状态标签页。",
"Error: %s": "错误: %s",
"Writing rules and reloading qosify...": "正在写入规则并重载 qosify...",
"Rules saved": "规则已保存",
"Clear editor": "清空编辑器",
"Empty the config editor? Nothing is written until you click Save & Apply.": "清空配置编辑器？在点击保存并应用前不会写入任何内容。",
"Empty the rules editor? Nothing is written until you click Save & Apply.": "清空规则编辑器？在点击保存并应用前不会写入任何内容。",
"No files selected.": "未选择文件。",
"Overwrite config files": "覆盖配置文件",
"The selected files replace the ones on the router and qosify is reloaded. Download a backup from this tab first if you need one.": "所选文件将替换路由器上的文件，并重载 qosify。如需备份，请先在此标签页下载。",
"Upload and apply": "上传并应用",
"Empty file": "空文件",
"File too large (max 64KB)": "文件过大（最大 64KB）",
"Read error": "读取错误",
"No valid UCI config stanzas": "无有效的 UCI 配置段",
"Uploading": "正在上传",
"Reading and validating files...": "正在读取并验证文件...",
"Config: %s": "配置: %s",
"Rules: %s": "规则: %s",
"Upload error: %s": "上传错误: %s",
"%s uploaded, qosify reloaded.": "%s 已上传，qosify 已重载。",
"Errors:": "错误:",
"Upload failed: %s": "上传失败: %s",
"Reset to defaults": "重置为默认值",
"%s and %s are replaced with the templates shipped by the qosify package, and shaping is left disabled.": "%s 和 %s 会被替换为 qosify 软件包自带的模板，且整形保持禁用。",
"Resetting": "正在重置",
"Restoring defaults...": "正在还原默认值...",
"%s was not written: %s": "%s 未能写入: %s",
"%s was reset but %s was not written: %s": "%s 已重置，但 %s 未能写入: %s",
"Reset to defaults, applied.": "已重置为默认值并应用。",
"Reset failed: %s": "重置失败: %s",
"Enter a value.": "输入一个值。",
"No classes defined. Add classes in the Config tab first.": "未定义类别。请先在配置标签页中添加类别。",
"Port must be a number or a range (4500, 5060-5061).": "端口必须是数字或范围（4500、5060-5061）。",
"Port must be 1-65534 (qosify rejects 65535).": "端口必须在 1-65534 之间（qosify 拒绝 65535）。",
"Range start must not exceed end.": "范围起点不能超过终点。",
"No spaces or # allowed in patterns or addresses.": "模式或地址中不允许包含空格或 #。",
"Enter a single IPv4 address (qosify does not accept CIDR).": "输入单个 IPv4 地址（qosify 不接受 CIDR）。",
"Enter a single IPv6 address (qosify does not accept CIDR or a %zone suffix).": "输入单个 IPv6 地址（qosify 不接受 CIDR 或 %zone 后缀）。",
"Enter a section name.": "输入小节名称。",
"A section name may only contain letters, digits and underscores.": "小节名称只能包含字母、数字和下划线。",
"A config defaults section already exists.": "已存在 config defaults 小节。",
"Section %s already exists.": "小节 %s 已存在。",
"%s could not be read — the editor is left empty and will not be saved over it.": "%s 无法读取 — 编辑器保持为空，且不会保存覆盖它。",
"%s changed on disk — your unsaved edits are still in the editor.": "%s 在磁盘上已发生变化 — 你未保存的修改仍在编辑器中。"
}

def translate(path):
    src = open(path, encoding='utf-8').read()
    pat = re.compile(r"(cat > \"\$VIEW_DIR/main\.js\" << 'JSEOF'\n)(.*?)(\nJSEOF)", re.S)
    m = pat.search(src)
    if not m:
        sys.exit('ERROR: main.js heredoc not found in ' + path)
    js = m.group(2)
    n = 0
    for k, v in T.items():
        p = re.compile(r"_\(\s*'" + re.escape(k) + r"'\s*\)")
        js, c = p.subn("_('" + v + "')", js)
        n += c
    open(path, 'w', encoding='utf-8').write(src[:m.start(2)] + js + src[m.end(2):])
    return n

if __name__ == '__main__':
    n = translate(sys.argv[1])
    print('translated', n, 'strings ->', sys.argv[1])
